$(document).ready(function(){
    console.log("hello")
    $("#signup-form").validate({
        rules:{
            yourname:{
                required:true,
                minlength:4
            }, 
            emailAddress:{
                required:true,
                email:true
            },
            subject:{
                required:true,
            },
            message:{
                required:true,
            }
        }
    })
})